### ISSUE TITLE
Implemente GeodeticUTMConverter.m

### ISSUE THREAD

**Issue by desimmon** [palmerc/GeodeticUTMConverter#1]
Hello, how i can implemente this?? i have tried all and i can't make work... I need to convert longitude and latitude to utm. Please help

**Comment by palmerc** [comment]
OK. Did you see there is a sample project? Did you install it as a
Cocoapod?

Can you give me an example of what you want to convert?

**Comment by desimmon** [comment]
Im getting current location coordinates with CLLocation. I have longitude and latitude in degrees geodesic in two labels in the screen. I need to put another labels to show in realtime the conversion of this geo coordinates to UTM...

Sorry for my english, im from spain. Thanks i hope you can help me

**Comment by palmerc** [comment]
From the Tests you can find this:

 CLLocationCoordinate2D coordinates;

```
coordinates.latitude = 59.912814611065265;

coordinates.longitude = 10.760192985178369;


GeodeticUTMConverter *utmConverter = [[GeodeticUTMConverter alloc] init
```

];

```
UTMCoordinates utmCoordinates = [utmConverter
```

latitudeAndLongitudeToUTMCoordinates:coordinates];

```
NSString *hemisphere;

if (utmCoordinates.hemisphere == kUTMHemisphereNorthern) {

    hemisphere = @"Northern";

} else {

    hemisphere = @"Southern";

}



NSLog(@"Northing: %f, Easting: %f, GridZone: %d, Hemisphere: %@",
```

utmCoordinates.northing, utmCoordinates.easting, utmCoordinates.gridZone,
hemisphere);

**Comment by desimmon** [comment]
Thanks i will try this and comment to you. Lot of thanks

**Comment by desimmon** [comment]
It works!!! Thanks a lot...
